// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEPsNfrELMJI1aju1m07OByXkl4OYIG8U',
    appId: '1:321274768267:web:e1bca4ad61a1ce16e4dd8e',
    messagingSenderId: '321274768267',
    projectId: 'fir-login-9c531',
    authDomain: 'fir-login-9c531.firebaseapp.com',
    storageBucket: 'fir-login-9c531.firebasestorage.app',
    measurementId: 'G-DM007HRPYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB01ktgYHf5rBpKEeRGlhqlT_NdI97zKPY',
    appId: '1:321274768267:android:891b48a0b6b28855e4dd8e',
    messagingSenderId: '321274768267',
    projectId: 'fir-login-9c531',
    storageBucket: 'fir-login-9c531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpPCpU9w09f9UYwJQSWDnFVqBFewPt9EM',
    appId: '1:321274768267:ios:4bd4c3b9c441ba51e4dd8e',
    messagingSenderId: '321274768267',
    projectId: 'fir-login-9c531',
    storageBucket: 'fir-login-9c531.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpPCpU9w09f9UYwJQSWDnFVqBFewPt9EM',
    appId: '1:321274768267:ios:4bd4c3b9c441ba51e4dd8e',
    messagingSenderId: '321274768267',
    projectId: 'fir-login-9c531',
    storageBucket: 'fir-login-9c531.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEPsNfrELMJI1aju1m07OByXkl4OYIG8U',
    appId: '1:321274768267:web:d8f8e51510737b93e4dd8e',
    messagingSenderId: '321274768267',
    projectId: 'fir-login-9c531',
    authDomain: 'fir-login-9c531.firebaseapp.com',
    storageBucket: 'fir-login-9c531.firebasestorage.app',
    measurementId: 'G-K5T4YQHGXL',
  );
}
