// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA5p7i6lHAXtcFDkV7gGBcx6TzyHHRBK4',
    appId: '1:343028789071:web:52d9a4d381c208d6161f3a',
    messagingSenderId: '343028789071',
    projectId: 'todolist-e2229',
    authDomain: 'todolist-e2229.firebaseapp.com',
    storageBucket: 'todolist-e2229.firebasestorage.app',
    measurementId: 'G-BGN9MDJ7WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFVU7Aspp6VZOTx4r_09S8LA29XbYGsHM',
    appId: '1:343028789071:android:9c96cbe764788fa7161f3a',
    messagingSenderId: '343028789071',
    projectId: 'todolist-e2229',
    storageBucket: 'todolist-e2229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAArzV_OZOrvTIrMI4lTytdVMdIc-9lmk4',
    appId: '1:343028789071:ios:e459dcb9b3181355161f3a',
    messagingSenderId: '343028789071',
    projectId: 'todolist-e2229',
    storageBucket: 'todolist-e2229.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAArzV_OZOrvTIrMI4lTytdVMdIc-9lmk4',
    appId: '1:343028789071:ios:e459dcb9b3181355161f3a',
    messagingSenderId: '343028789071',
    projectId: 'todolist-e2229',
    storageBucket: 'todolist-e2229.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA5p7i6lHAXtcFDkV7gGBcx6TzyHHRBK4',
    appId: '1:343028789071:web:96b6f5f877aa5bc5161f3a',
    messagingSenderId: '343028789071',
    projectId: 'todolist-e2229',
    authDomain: 'todolist-e2229.firebaseapp.com',
    storageBucket: 'todolist-e2229.firebasestorage.app',
    measurementId: 'G-5LTWXY3DYQ',
  );
}
