// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRgPnQJ29UflOvixTbqwt5cnZvrOOfmoY',
    appId: '1:829189942319:web:897334ed8b4cd9720b6ada',
    messagingSenderId: '829189942319',
    projectId: 'first-crude-project',
    authDomain: 'first-crude-project.firebaseapp.com',
    databaseURL: 'https://first-crude-project-default-rtdb.firebaseio.com',
    storageBucket: 'first-crude-project.firebasestorage.app',
    measurementId: 'G-8Z5H9Q94QD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjGm4yfiuHU2Il7pvJBJZVVXoE5tNZN5Q',
    appId: '1:829189942319:android:308734cd4edec6430b6ada',
    messagingSenderId: '829189942319',
    projectId: 'first-crude-project',
    databaseURL: 'https://first-crude-project-default-rtdb.firebaseio.com',
    storageBucket: 'first-crude-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnW3dUpSR0XjxHNEBLxKtMCYEX5i1Q5YQ',
    appId: '1:829189942319:ios:f1e60bab0ee725580b6ada',
    messagingSenderId: '829189942319',
    projectId: 'first-crude-project',
    databaseURL: 'https://first-crude-project-default-rtdb.firebaseio.com',
    storageBucket: 'first-crude-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnW3dUpSR0XjxHNEBLxKtMCYEX5i1Q5YQ',
    appId: '1:829189942319:ios:f1e60bab0ee725580b6ada',
    messagingSenderId: '829189942319',
    projectId: 'first-crude-project',
    databaseURL: 'https://first-crude-project-default-rtdb.firebaseio.com',
    storageBucket: 'first-crude-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRgPnQJ29UflOvixTbqwt5cnZvrOOfmoY',
    appId: '1:829189942319:web:1586ee080e79f54a0b6ada',
    messagingSenderId: '829189942319',
    projectId: 'first-crude-project',
    authDomain: 'first-crude-project.firebaseapp.com',
    databaseURL: 'https://first-crude-project-default-rtdb.firebaseio.com',
    storageBucket: 'first-crude-project.firebasestorage.app',
    measurementId: 'G-BQM5K5NZNL',
  );
}
